# Generated by Django 5.0.6 on 2024-06-02 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassCategory",
            fields=[
                (
                    "cid",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "class_number",
                    models.BigIntegerField(
                        help_text="第幾屆的分類", unique=True, verbose_name="屆數"
                    ),
                ),
                (
                    "student_count",
                    models.IntegerField(default=0, verbose_name="該屆學生人數"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用該屆所有帳號"),
                ),
            ],
            options={
                "db_table": "class_category",
            },
        ),
        migrations.CreateModel(
            name="StudentAccount",
            fields=[
                (
                    "sid",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "class_number",
                    models.BigIntegerField(help_text="第幾屆的分類", verbose_name="屆數"),
                ),
                ("username", models.CharField(max_length=10, verbose_name="學生學號")),
                ("name", models.CharField(max_length=50, verbose_name="學生姓名")),
                ("join_date", models.DateField(auto_now_add=True)),
                ("last_edit_date", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "student_account",
            },
        ),
        migrations.CreateModel(
            name="StudentProgram",
            fields=[
                (
                    "program_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("program_name", models.CharField(max_length=20)),
                ("html_code", models.TextField(blank=True, null=True)),
                ("javascript_code", models.TextField(blank=True, null=True)),
                ("css_code", models.TextField(blank=True, null=True)),
                ("join_date", models.DateField(auto_now_add=True)),
                ("last_edit_date", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "student_program",
            },
        ),
    ]
