# Generated by Django 5.0.6 on 2024-05-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classify", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("acc", models.CharField(max_length=20)),
                ("psw", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "accounts",
            },
        ),
    ]
