# Generated by Django 5.0.6 on 2024-06-02 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprogram",
            name="sid",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="backend.studentaccount",
            ),
        ),
    ]
